import os
import subprocess

from iwiki_mcp import base, indexer, server
from iwiki_mcp.engine.store import VectorStore


def _git_init(base_dir):
    """Turn the seeded base into a real (remote-less) git repo so commit_and_push
    actually commits — the default _seed base is not a repo."""
    for args in (["init", "-q"], ["config", "user.email", "t@t"],
                 ["config", "user.name", "t"],
                 ["commit", "--allow-empty", "-qm", "init"]):
        subprocess.run(["git", "-C", base_dir, *args], check=True)


def _committed_files(base_dir):
    out = subprocess.run(["git", "-C", base_dir, "show", "--name-only",
                          "--format=", "HEAD"], capture_output=True, text=True)
    return out.stdout.split()


def _seed(tmp_path, monkeypatch):
    b = tmp_path / "wiki"
    (b / "backend" / ".iwiki").mkdir(parents=True)
    proj = tmp_path / "proj"
    proj.mkdir()
    (proj / ".iwiki.toml").write_text('read = ["backend"]\nwrite = "backend"\n')
    monkeypatch.setenv("IWIKI_BASE_DIR", str(b))
    monkeypatch.setenv("IWIKI_PROJECT_DIR", str(proj))
    monkeypatch.setenv("IWIKI_LLM_BASE_URL", "http://x/v1")
    monkeypatch.setenv("IWIKI_LLM_KEY", "k")
    monkeypatch.setenv("IWIKI_EMBED_DIMENSIONS", "2")
    monkeypatch.setattr(indexer, "embed_texts", lambda cfg, t: [[1.0, 0.0] for _ in t])
    return str(b)


def test_write_refreshes_okf_artifacts(tmp_path, monkeypatch):
    b = _seed(tmp_path, monkeypatch)
    server.wiki_write_page("backend", "auth", "# Auth\n\n## Overview\ns\n\n## Flow\nx\n")
    dom = os.path.join(b, "backend")
    assert os.path.isfile(os.path.join(dom, "index.md"))
    assert os.path.isfile(os.path.join(dom, "log.md"))
    assert "[auth](auth.md)" in open(os.path.join(dom, "index.md"), encoding="utf-8").read()


def test_reserved_files_not_indexed(tmp_path, monkeypatch):
    b = _seed(tmp_path, monkeypatch)
    server.wiki_write_page("backend", "auth", "# Auth\n\n## Overview\ns\n\n## Flow\nx\n")
    server.wiki_index("backend")            # reindex with index.md/log.md present
    recs = VectorStore(base.index_path(b, "backend")).load()
    assert all(r.file not in ("index.md", "log.md") for r in recs)


def test_delete_refreshes_index(tmp_path, monkeypatch):
    b = _seed(tmp_path, monkeypatch)
    server.wiki_write_page("backend", "auth", "# Auth\n\n## Overview\ns\n\n## Flow\nx\n")
    server.wiki_write_page("backend", "db", "# DB\n\n## Overview\ns\n\n## Schema\nx\n")
    server.wiki_delete_page("backend", "auth")
    idx = open(os.path.join(b, "backend", "index.md"), encoding="utf-8").read()
    assert "[db](db.md)" in idx and "auth.md" not in idx


def test_write_rejects_reserved_slug(tmp_path, monkeypatch):
    b = _seed(tmp_path, monkeypatch)
    out = server.wiki_write_page("backend", "index", "# I\n\n## Overview\nx\n")
    assert "error" in out and "reserved" in out["error"]
    assert not os.path.isfile(os.path.join(b, "backend", "index.md"))


def test_write_rejects_reserved_slug_on_established_domain(tmp_path, monkeypatch):
    # On any domain with a prior successful write, index.md/log.md already exist
    # (refresh_artifacts generated them). The reserved guard must still fire —
    # not the misleading "page exists" error that invites editing via update_page.
    b = _seed(tmp_path, monkeypatch)
    server.wiki_write_page("backend", "auth", "# Auth\n\n## Overview\ns\n\n## Flow\nx\n")
    idx_path = os.path.join(b, "backend", "index.md")
    assert os.path.isfile(idx_path)                       # generated by the first write
    out = server.wiki_write_page("backend", "index", "# I\n\n## Overview\nx\n")
    assert "error" in out
    assert "reserved" in out["error"] and "exists" not in out["error"]
    assert "[auth](auth.md)" in open(idx_path, encoding="utf-8").read()   # not overwritten


def test_reserved_link_sections_not_indexed_but_graphed(tmp_path, monkeypatch):
    # SC-3: reserved `## Outgoing links` / `## External links` sections never enter
    # the vector store as *section* records, but the page-to-page edges they carry
    # still reach `wiki_related`'s link graph. `target`'s only section is reserved, so
    # it contributes no section record (only its summary record from the frontmatter
    # description); `alice.md#Role` is the domain's only section record, so
    # `related()`'s vector-neighbour lookup (section-only) is empty and its graph
    # fallback runs -- proving the edge, not a vector-similarity coincidence.
    b = _seed(tmp_path, monkeypatch)
    server.wiki_write_page("backend", "target",
                           "# Target\n\n## External links\n- https://example.com/target\n",
                           source=None, type="concept", description="target page")
    page = ("# Alice\n\n## Role\nbilling prose here.\n\n"
            "## Outgoing links\n- [Target](target.md)\n\n"
            "## External links\n- https://example.com/docs\n")
    server.wiki_write_page("backend", "alice", page, source=None, type="person",
                           description="Alice covers billing.")
    recs = VectorStore(base.index_path(b, "backend")).load()
    # target's reserved section is never indexed as a section (only its summary lands)
    assert not any(r.file == "target.md" and r.kind == "section" for r in recs)
    alice_secs = [r for r in recs if r.file == "alice.md" and r.kind == "section"]
    headings = {r.heading for r in alice_secs}
    assert headings == {"Role"}                      # link sections not indexed
    # the authored outgoing link still feeds the graph
    rel = server.wiki_related("backend", "alice.md#Role")
    assert rel["graph"] == ["target"]
    assert "target" in str(rel)


def test_reserved_files_land_in_the_same_commit(tmp_path, monkeypatch):
    # Load-bearing: the generated index.md/log.md must be committed alongside the
    # page in ONE commit. The default _seed base is not a git repo, so this is the
    # only test that exercises commit_and_push's `git add -- <domain>` staging the
    # new untracked reserved files. Guards against a regression to `git add -u`.
    b = _seed(tmp_path, monkeypatch)
    _git_init(b)
    out = server.wiki_write_page("backend", "auth",
                                 "# Auth\n\n## Overview\ns\n\n## Flow\nx\n")
    assert out.get("committed") is True
    files = _committed_files(b)
    assert "backend/index.md" in files
    assert "backend/log.md" in files
    assert "backend/auth.md" in files
